### ISSUE TITLE
Clean up offer accept/decline code in example framework

### ISSUE THREAD

**Issue by cruhland** [mesosphere/mesos-rxjava#10]
- The variable `Observable<Call> declines` should be renamed to `evaluatedOffers` or something similar
- The offer should be declined (instead of ignored) in the `else` block corresponding with `if (cpuList != null && !cpuList.isEmpty() && memList != null && !memList.isEmpty())`.

**Comment by BenWhitehead** [comment]
Done some time ago, and still fixed as of [4b25f84](https://github.com/mesosphere/mesos-rxjava/blob/4b25f845c86fe0592ff5afb94e91d89b9d55a745/mesos-rxjava-example/mesos-rxjava-example-framework/src/main/java/com/mesosphere/mesos/rx/java/example/framework/sleepy/Sleepy.java#L177).
