### ISSUE TITLE
Handle redirect responses for SUBSCRIBE calls

### ISSUE THREAD

**Issue by cruhland** [mesosphere/mesos-rxjava#14]
As described in the "Master detection" section of the [Scheduler HTTP API docs](http://mesos.apache.org/documentation/latest/scheduler-http-api/) (bottom of page), `SUBSCRIBE` requests will receive a 307 response status code (Temporary Redirect) if sent to a non-leading Mesos master. The response will include a `Location` header with the host and port of the leading master.

The `MesosSchedulerClient` should handle this possibility automatically, for user convenience.

**Comment by BenWhitehead** [comment]
Duplicate of #18
