### ISSUE TITLE
Prevent invalid subscribe calls

### ISSUE THREAD

**Issue by cruhland** [mesosphere/mesos-rxjava#7]
Currently `MesosClientScheduler.openEventStream()` takes an argument that is expected to be a valid subscribe call to Mesos. There's no validation of the argument though, so any type of call could be passed in, giving unexpected results. Let's figure out the best way to prevent or mitigate invalid calls.

**Comment by BenWhitehead** [comment]
Mesos is the authority on what is valid/not valid. As long as the type can be constructed and has a corresponding codec the error handling should be left up to Mesos and the user.
