### ISSUE TITLE
How to convert v1 Offer to v0 Offer

### ISSUE THREAD

**Issue by zonybob** [mesosphere/mesos-rxjava#74]
I am converting a Netflix Fenzo-based scheduler to use the HTTP API. One issue I'm encountering is that several of Fenzo's methods accept `org.apache.mesos.Protos.Offer`. Of course, in my new HTTP-based scheduler, I am receiving `org.apache.mesos.v1.Protos.Offer`. Is there a clean way to convert from the v1 Protos.Offer to the old Protos.Offer so that I can give it to Fenzo?

**Comment by zonybob** [comment]
For what it's worth, I've been testing with something like...


```
        Protos.Offer v1 = SchedulerEvents.resourceOffer(
                "vm01",
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                UUID.randomUUID().toString(),
                0.1,
                16,
                100
        ).getOffers().getOffers(0);

        LOG.info(v1.toString());

        org.apache.mesos.Protos.Offer v0 = org.apache.mesos.Protos.Offer.parseFrom(v1.toByteArray());

        LOG.info(v0.toString());

        Assert.assertEquals(v0.getHostname(), v1.getHostname());
        Assert.assertEquals(v0.toByteString(), v1.toByteString());

```
It **seems** like it converts OK, but I don't trust it, and there's nothing in the Mesos docs that indicates this is safe. Any thoughts?

**Comment by BenWhitehead** [comment]
I'm not aware of anything that provides a safe conversion from a mesos v1 proto to a v0 proto. Manual mapping could in theory work, but I would be afraid of some changes in v1 that might make it incompatible with v0.

This would probably be a good question to ask on the mesos user mailing list or in their slack[1].

[1] https://mesos.apache.org/community/

**Comment by zonybob** [comment]
OK, thanks again for the quick reply. I might post this to Fenzo and Mesos to see what they say.

**Comment by BenWhitehead** [comment]
Sounds good, feel free to ping back here if you find anything out.

**Comment by zonybob** [comment]
FWIW, on Mesos Slack, someone pointed me to this link. The class notes that Mesos uses the same conversion logic internally, so that was good enough for me. It is basically serialize, deserialize... but using the builder.merge. 

https://github.com/apache/aurora/blob/c85bffdd6f68312261697eee868d57069adda434/src/main/java/org/apache/aurora/scheduler/mesos/ProtosConversion.java
