### ISSUE TITLE
Provide method to submit call outside the event stream

### ISSUE THREAD

**Issue by zonybob** [mesosphere/mesos-rxjava#75]
In my specific scheduler, I use Netflix Fenzo to accumulate (a) Mesos resource offers and (b) Kafka-driven TaskRequests. Fenzo then evaluates the available resources and the needs of my tasks to give back optimal assignments. The issue I'm having with mesos-rxjava is that Fenzo does this asynchronously. I don't have a logical place within the event stream to accept an offer from Mesos and then launch tasks. In other words, in my current, v0, MesosSchedulerDriver scheduler, my decision to launch a task is driven by Fenzo's callback ... not by Mesos.

So with that, to use mesos-rxjava, it seems like I have to just publish/produce my intentions to launch tasks from the Fenzo callback, and then poll/consume those from the rx event stream... perhaps after the heartbeat event.

Three questions:

1. Am I missing something? Is there already a way to asynchrously launch tasks outside the event stream?
2. If there is no way, then is my workaround reasonable? (effectively launching accumulated TaskInfos  as a SinkOperation from the heartbeat Event)
3. Do you think that in the future, mesos-rxjava could provide a hook to issue a Call outside the event stream?

**Comment by BenWhitehead** [comment]
Hi @zonybob, This can already be done and in fact a few people are already doing something similar.

Here is a link  to a https://github.com/mesosphere/mesos-rxjava/pull/63#issuecomment-235043568 I made that describes how this can be done without having to change anything in mesos-rxjava.

The nice thing with that approach is that you don't have to build a buffer and flush it on heartbeat or anything like that, just fire it through the subject and it will go off like an event being processed immediately.

**Comment by zonybob** [comment]
This sounds great. I'll take a look and try it out. Thanks for the quick response!

**Comment by BenWhitehead** [comment]
Sure, I'm going to close this in favor of the docs issue I opened above.
